apiVersion: v1
kind: Pod
metadata:
   name: fluentd-gelf
   namespace: default
labels:
   k8s-app: fluentd-gelf
spec:
   containers:
   - name: docker-fluentd-kubernetes-gelf
     image: damien/docker-fluentd-kubernetes-gelf-ovh
     imagePullPolicy: Always
     env:
       - name: OVH_TOKEN
         value: "TOKEN OVH ICI"
       - name: GELF_HOST
         value: "laas.runabove.com"
       - name: GELF_PORT
         value: "12202"
     volumeMounts:
       - name: varlog
         mountPath: /var/log
       - name: varlibdockercontainers
         mountPath: /var/lib/docker/containers
     readOnly: true
     terminationGracePeriodSeconds: 30
     Resources:
      limits:
         memory: 200Mi
      Requests:
         cpu: 100m
         memory: 200Mi
   imagePullSecrets:
     - name: actigraphregistrycred
   volumes:
     - name: varlog
       hostPath:
        path: /var/log
     - name: varlibdockercontainers
       hostPath:
        path: /var/lib/docker/containers
